const PrismaBaseRepository = require('./_prismaBase');

function repo(name) {
  return new PrismaBaseRepository(name);
}

module.exports = {
  userRepo: repo('users'),
  courseRepo: repo('courses'),
  lessonRepo: repo('lessons'),
  unitRepo: repo('units'),
  videoRepo: repo('videos'),
  lessonFileRepo: repo('lessonFiles'),
  questionBankRepo: repo('questionBanks'),
  quizRepo: repo('quizzes'),
  questionRepo: repo('questions'),
  choiceRepo: repo('choices'),
  subscriptionRepo: repo('subscriptions'),
  userSubscriptionRepo: repo('userSubscriptions'),
  enrollmentRepo: repo('enrollments'),
  paymentRepo: repo('payments'),
  subRequestRepo: repo('subRequests'),
  examAttemptRepo: repo('examAttempts'),
  examAnswerRepo: repo('examAnswers'),
  noteRepo: repo('notes'),
  notificationRepo: repo('notifications'),
  reviewRepo: repo('reviews'),
  reviewVideoRepo: repo('reviewVideos'),
  reviewFileRepo: repo('reviewFiles'),
  announcementRepo: repo('announcements'),
  ticketRepo: repo('supportTickets'),
  ticketReplyRepo: repo('ticketReplies'),
  settingRepo: repo('settings'),
  chargeCodeRepo: repo('chargeCodes'),
  liveSessionRepo: repo('liveSessions'),
  chatSessionRepo: repo('chatSessions'),
  chatMessageRepo: repo('chatMessages'),
  chatAttachmentRepo: repo('chatAttachments'),
  zoomCredentialRepo: repo('zoomCredentials'),
  zoomAppCredentialRepo: repo('zoomAppCredentials'),
  parentInviteRepo: repo('parentInvites'),
  studentAnalyticRepo: repo('studentAnalytics'),
  systemStatRepo: repo('systemStats'),
  contactMessageRepo: repo('contactMessages'),
  cronClaimRepo: repo('cronClaims'),
  dismissedRepo: repo('dismisseds'),
  videoProgressRepo: repo('videoProgress'),
  lessonProgressRepo: repo('lessonProgress'),
  referralRepo: repo('referrals'),
  childRelationRepo: repo('childRelations'),
  subscriptionFeatureRepo: repo('subscriptionFeatures'),
  planAllowedCourseRepo: repo('planAllowedCourses'),
  auditLogRepo: repo('auditLogs'),
  refreshTokenRepo: repo('refreshTokens'),
  PrismaBaseRepository,
};
